services:
  database:
    image: mysql:8.0
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: csd
      MYSQL_USER: user
      MYSQL_PASSWORD: 5up3r53cr3t
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD:-rootpassword} --execute "SHOW DATABASES;" || exit 0',
        ]
      start_interval: 10s
      interval: 1s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  app:
    image: 205930623194.dkr.ecr.eu-central-1.amazonaws.com/connectivity-service-development/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      CSD_DB_URL: jdbc:mysql://db:3306/csd
      CSD_DB_USER: user
      CSD_DB_PASSWORD: 5up3r53cr3t
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
