include: package:lints/recommended.yaml

analyzer:
  exclude: [lib/**.g.dart,lib/**.config.dart,test/**.mocks.dart]
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true

linter:
  rules:
    - cancel_subscriptions
    - prefer_relative_imports
    - directives_ordering
    - avoid_print