// Mocks generated by Mockito 5.4.4 from annotations
// in connect_service_app/test/feature/dashboard/presentation/cubit/dashboard_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:connect_service_app/feature/dashboard/domain/entity/dashboard_entry.dart'
    as _i4;
import 'package:connect_service_app/feature/dashboard/domain/service/dashboard_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DashboardService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardService extends _i1.Mock implements _i2.DashboardService {
  MockDashboardService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.DashboardEntry>> readProducts() => (super.noSuchMethod(
        Invocation.method(
          #readProducts,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.DashboardEntry>>.value(<_i4.DashboardEntry>[]),
      ) as _i3.Future<List<_i4.DashboardEntry>>);
}
